// SkyGlobe Group — blog post data
// Loaded lazily on first visit to the Blog page (not on initial HTML parse).
// Add new posts here — the blog page picks them up automatically.
window.BLOG_POSTS=[
  {
    id:1,cat:'Visa Guide',thumb:'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=600&q=80&auto=format&fit=crop',
    title:'How to Get a UK Visa in 2025: Complete Step-by-Step Guide',
    excerpt:'Everything you need to know about UK visa categories, documents required, processing times, and how to maximise your approval chances.',
    date:'Jun 10, 2026',readTime:'8 min read',
    content:`<h3>Understanding UK Visa Categories</h3><p>The UK offers several visa types depending on your purpose of visit. The most common are the Standard Visitor Visa (B1/B2 equivalent), Student Visa (formerly Tier 4), Skilled Worker Visa (formerly Tier 2), and the Graduate Visa for post-study stay.</p><h3>Key Documents Required</h3><p>Every UK visa application requires: a valid passport (at least 6 months validity), bank statements covering 3–6 months, accommodation proof, travel itinerary, and the correct visa application fee. Additional documents vary by visa type.</p><h3>Processing Times</h3><p>Standard processing is 3 weeks. Priority processing (£500 extra) typically takes 5 working days. Super Priority (£800 extra) gives a next working day decision for most visas.</p><h3>Tips for Success</h3><ul><li>Apply at least 3 months before your planned travel date</li><li>Show strong ties to your home country (property, employment, family)</li><li>Ensure bank statements show consistent, adequate funds — not a sudden large deposit</li><li>Use a professional consultant for complex cases</li></ul><p>SkyGlobe has processed over 3,000 successful UK visa applications. <a onclick="showPage('contact')" style="color:var(--gold);cursor:pointer">Book a free consultation</a> to get personalised guidance.</p>`
  },
  {
    id:2,cat:'Study Abroad',thumb:'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=600&q=80&auto=format&fit=crop',
    title:'Top 10 Universities to Apply for International Students in 2025',
    excerpt:'From Oxbridge to MIT, we rank the best universities for international students based on scholarships, acceptance rates, and post-study work options.',
    date:'Jun 7, 2026',readTime:'6 min read',
    content:`<h3>Why University Choice Matters</h3><p>Choosing the right university determines not just your education quality but your visa options, scholarship eligibility, and post-study work rights. Here are our top picks for international students in 2025.</p><h3>United Kingdom</h3><ul><li><strong>University of Oxford</strong> — QS Rank #3, Clarendon Scholarships available</li><li><strong>University of Cambridge</strong> — QS Rank #2, Gates-Cambridge fully funded</li><li><strong>Imperial College London</strong> — Top for STEM, strong industry links</li></ul><h3>Canada</h3><ul><li><strong>University of Toronto</strong> — #25 globally, PGWP eligible</li><li><strong>McGill University</strong> — Affordable tuition, bilingual environment</li></ul><h3>Australia</h3><ul><li><strong>University of Melbourne</strong> — Graduate Visa (485) available after graduation</li><li><strong>ANU Canberra</strong> — Strong research programs, regional visa benefits</li></ul><h3>Germany (Tuition-Free)</h3><ul><li><strong>LMU Munich</strong> — Virtually free education, strong industry partnerships</li><li><strong>TU Berlin</strong> — Top engineering school, ~€375/semester</li></ul><p>Ready to apply? Our admissions team has placed students in all these institutions. <a onclick="showPage('apply')" style="color:var(--gold);cursor:pointer">Start your application today.</a></p>`
  },
  {
    id:3,cat:'EU Employment',thumb:'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&q=80&auto=format&fit=crop',
    title:'EU Direct Employment: How Africans Are Building Careers in Europe',
    excerpt:'Poland, Portugal, Latvia and beyond — skilled workers from Africa are securing EU jobs through legal placement programmes. Here\'s how.',
    date:'Jun 3, 2026',readTime:'7 min read',
    content:`<h3>The EU Labour Shortage Opportunity</h3><p>Europe is facing a historic labour shortage over 3 million unfilled positions across healthcare, construction, IT, and hospitality. For skilled workers from Africa and Asia, this creates an unprecedented legal pathway into the EU.</p><h3>Most In-Demand Roles</h3><ul><li>Healthcare: nurses, caregivers, medical staff</li><li>Construction: civil engineers, site managers, skilled tradespeople</li><li>IT & Technology: software developers, data analysts, cybersecurity</li><li>Hospitality: hotel managers, chefs, service professionals</li></ul><h3>Countries with Fastest Processing</h3><p><strong>Poland</strong> — National Visa D, processing 2–4 weeks. Strong economy, affordable living. <strong>Portugal</strong> — D3 Highly Qualified Visa, pathway to EU permanent residence in 5 years. <strong>Latvia</strong> — EU Blue Card available, gateway to all 27 EU countries.</p><h3>The SkyGlobe Placement Process</h3><p>We match you with verified EU employers, handle your work permit application, assist with accommodation finding, and provide pre-departure orientation. Success rate: 96% of placed candidates are still employed after 12 months.</p><p><a onclick="showPage('contact')" style="color:var(--gold);cursor:pointer">Apply for EU placement →</a></p>`
  },
  {
    id:4,cat:'Immigration Tips',thumb:'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&q=80&auto=format&fit=crop',
    title:'Common Visa Rejection Reasons (And How to Avoid Them)',
    excerpt:'Our analysis of 500+ rejected visa applications reveals the most common mistakes — and the simple fixes that turn rejections into approvals.',
    date:'May 28, 2026',readTime:'5 min read',
    content:`<h3>The Most Common Rejection Reason: Financial Evidence</h3><p>Over 60% of visa rejections come down to inadequate financial documentation. Officers want to see consistent savings over 3–6 months, not a sudden large transfer the week before application. Aim for funds equal to twice your stated trip cost.</p><h3>Weak Ties to Home Country</h3><p>The officer must believe you will return home. Strengthen your ties with: employment letter showing approved leave and return date, property ownership or long-term rental agreement, family connections (especially dependent children), and an active business in your country.</p><h3>Incomplete Documentation</h3><p>Missing documents are an instant rejection. Use our official document checklists (available when you <a onclick="showPage('apply')" style="color:var(--gold);cursor:pointer">start your application</a>) to ensure nothing is missing.</p><h3>Vague or Inconsistent Information</h3><p>Your bank statement, employment letter, and application form must all tell the same story. Inconsistencies — even minor ones — raise red flags. Have a professional review your application before submission.</p><h3>Bad Timing</h3><p>Applying too close to your travel date suggests poor planning. Apply 8–12 weeks ahead for standard visas to allow time for any document requests without missing your trip.</p>`
  },
  {
    id:5,cat:'Travel Tips',thumb:'https://images.unsplash.com/photo-1488085061387-422e29b40080?w=600&q=80&auto=format&fit=crop',
    title:'Travelling Abroad for the First Time: A Complete Preparation Guide',
    excerpt:'From packing your documents to arriving safely and setting up your new life — our first-timer\'s guide covers everything you need.',
    date:'May 22, 2026',readTime:'9 min read',
    content:`<h3>Before You Travel: Document Checklist</h3><p>Never leave home without: valid passport (6+ months), visa/entry permit, flight booking confirmations, accommodation proof, travel insurance, emergency contacts list, sufficient local currency or a card that works internationally.</p><h3>Travel Insurance: Non-Negotiable</h3><p>Medical emergencies abroad can cost $50,000+. Get travel insurance with at least $100,000 medical cover and trip cancellation protection. For students, check if your university requires specific coverage (e.g. OSHC for Australia, IHS for UK).</p><h3>Airport Arrival Tips</h3><ul><li>Have all documents in a single, accessible folder — not buried in your luggage</li><li>Immigration officers may ask about your plans — answer clearly and confidently</li><li>Declare any amounts over $10,000 in cash</li><li>Keep your SIM card functional until you get a local one</li></ul><h3>First Week Priorities</h3><ul><li>Register with your local authority/university within required timeframe</li><li>Open a local bank account</li><li>Register with a local GP (UK) or find a primary care physician</li><li>Connect with your country's embassy/consulate for emergency contacts</li></ul><p>SkyGlobe provides pre-departure orientation for all our clients. <a onclick="showPage('contact')" style="color:var(--gold);cursor:pointer">Book your consultation →</a></p>`
  },
  {
    id:6,cat:'World Cup 2026',thumb:'https://images.unsplash.com/photo-1543326727-cf6c39e8f84c?w=600&q=80&auto=format&fit=crop',
    title:'FIFA World Cup 2026: How to Get Your USA & Canada Visa Fast',
    excerpt:'The World Cup arrives in North America in 2026. We break down the fastest visa pathways for fans from Africa, Asia and beyond.',
    date:'Jun 12, 2026',readTime:'6 min read',
    content:`<h3>World Cup 2026: North America Hosts</h3><p>The 2026 FIFA World Cup will be hosted across the USA, Canada, and Mexico — marking the first time 3 countries co-host the tournament. 16 USA cities, 3 Canadian cities, and 3 Mexican cities will host 104 matches.</p><h3>Do I Need a Visa?</h3><p>Citizens of ESTA-eligible countries can visit the USA visa-free for up to 90 days. However, most African passport holders need a B-1/B-2 Tourist Visa for the USA and a Temporary Resident Visa (TRV) for Canada.</p><h3>Documents Needed for World Cup Visa</h3><ul><li>Match tickets purchased (print and keep the purchase confirmation)</li><li>Hotel or Airbnb booking for all nights</li><li>Flight reservations (not necessarily paid tickets)</li><li>Bank statements — typically $150–200/day minimum</li><li>Employment letter confirming approved leave</li><li>Cover letter explaining your travel plans match-by-match</li></ul><h3>Processing Timeline</h3><p>Start NOW. USA B-2 visa interviews are booking 3–6 months ahead. Canada TRV can process online in 2–8 weeks but we recommend applying immediately to avoid delays.</p><p>SkyGlobe offers a World Cup Visa Package with expedited processing and document preparation. <a onclick="showPage('contact')" style="color:var(--gold);cursor:pointer">Get started today →</a></p>`
  },
  {
    id:7,cat:'Scholarships',thumb:'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=600&q=80&auto=format&fit=crop',
    title:'10 Fully Funded Scholarships for African Students in 2025–2026',
    excerpt:'From Chevening to Fulbright to DAAD — a curated list of the most prestigious fully-funded scholarships you can still apply for this cycle.',
    date:'May 15, 2026',readTime:'7 min read',
    content:`<h3>Fully Funded = Zero Cost</h3><p>Fully funded scholarships cover tuition fees, living allowance, flights, and health insurance. These are the golden tickets — and many African students miss them simply because they don't know they exist.</p><h3>Top 10 Fully Funded Scholarships</h3><ul><li><strong>Chevening Scholarship (UK)</strong> — All expenses paid for any UK master's degree. Deadline: Nov 2026.</li><li><strong>Fulbright Program (USA)</strong> — Covers all costs for US graduate study. Applications open August.</li><li><strong>DAAD Scholarship (Germany)</strong> — Multiple programs for undergrad, masters, and PhD. Tuition-free country.</li><li><strong>Commonwealth Scholarship</strong> — Full funding for master's and PhD at UK universities. Nominated by home government.</li><li><strong>Erasmus+ (EU)</strong> — Study in any EU country. Full stipend + travel costs covered.</li><li><strong>Australia Awards</strong> — Australian government pays for full degree. Strong African allocation.</li><li><strong>Vanier CGS (Canada)</strong> — $50,000/year for 3 years for PhD students.</li><li><strong>MasterCard Foundation Scholars</strong> — Full funding for academically brilliant African youth.</li><li><strong>Gates-Cambridge (UK)</strong> — Full Cambridge University funding. Extremely competitive.</li><li><strong>Korean Government Scholarship (KGSP)</strong> — Korean language + full degree costs. Growing opportunity.</li></ul><p>Our scholarship team has helped students secure over $2 million in awards. <a onclick="showPage('contact')" style="color:var(--gold);cursor:pointer">Book a scholarship consultation →</a></p>`
  },
  {
    id:8,cat:'Life Abroad',thumb:'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=600&q=80&auto=format&fit=crop',
    title:'Cost of Living Comparison: UK vs Canada vs Australia vs Germany in 2025',
    excerpt:'A real breakdown of monthly expenses for international students and workers across four top destinations to help you plan your budget.',
    date:'May 8, 2026',readTime:'5 min read',
    content:`<h3>Monthly Cost Breakdown (Single Person, 2025)</h3><p>Understanding true living costs — beyond just tuition — is essential for financial planning abroad.</p><h3>United Kingdom (London)</h3><ul><li>Rent (student hall/shared): £800–1,200/month</li><li>Food & groceries: £300–450/month</li><li>Transport (Oyster): £100–180/month</li><li>Total estimate: £1,400–2,000/month</li></ul><h3>Canada (Toronto)</h3><ul><li>Rent (shared room): CAD $900–1,400/month</li><li>Food: CAD $400–600/month</li><li>Transport: CAD $150/month</li><li>Total estimate: CAD $1,500–2,200/month</li></ul><h3>Australia (Melbourne)</h3><ul><li>Rent (shared): AUD $800–1,200/month</li><li>Food: AUD $400–600/month</li><li>Transport: AUD $150/month</li><li>Total: AUD $1,400–2,000/month</li></ul><h3>Germany (Munich)</h3><ul><li>Rent (student hall): €500–900/month</li><li>Food: €250–400/month</li><li>Transport (semester ticket): ~€90/semester</li><li>Total: €800–1,400/month</li></ul><p><strong>Bottom line:</strong> Germany offers the best value — especially with near-free tuition. UK costs highest. All countries allow part-time work to offset expenses.</p>`
  }
];
